LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_C_INCLUDES += $(LOCAL_PATH)
LOCAL_MODULE     := JNIHelper
LOCAL_SRC_FILES  := JNIHelper.c
LOCAL_STATIC_LIBRARIES := JNIHelper

include $(BUILD_SHARED_LIBRARY)
