/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allen_androiddevcoder_activity_Activity_JINI */

#ifndef _Included_com_allen_androiddevcoder_activity_Activity_JINI
#define _Included_com_allen_androiddevcoder_activity_Activity_JINI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_allen_androiddevcoder_activity_Activity_JINI
 * Method:    getJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_allen_androiddevcoder_activity_Activity_1JINI_getJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
